# Generated by Django 3.2.9 on 2022-01-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20210511_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
